name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Create venv
        run: uv venv
      - name: Install dependencies
        run: uv pip install ".[dev]"
      - name: Run ruff
        run: uv run ruff check .

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Create venv
        run: uv venv
      - name: Install dependencies
        run: uv pip install ".[dev]"
      - name: Run pyright
        run: uv run pyright

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Create venv
        run: uv venv
      - name: Install dependencies
        run: uv pip install ".[dev]"
      - name: Run pytest
        run: uv run pytest tests/